### ISSUE TITLE
Can't import specific languages

### ISSUE THREAD

**Issue by Sergiobop** [forzagreen/n2words#107]
After upgrading to 1.16.1 i can't import specific languages:

From the wiki:
import n2wordsES from 'n2words/i18n/ES.js'
```
Cannot find module 'n2words/i18n/ES.js' or its corresponding type declarations.

import n2wordsES from 'n2words/i18n/ES.js';
```

If i change the import to
import n2wordsES from 'n2words/lib/i18n/ES.js';

```Error: Module not found: Error: Package path ./lib/i18n/ES.js is not exported from package node_modules/n2words (see exports field in node_modules/n2words/package.json)```

Downgrading to 1.15 since it works as spected:
```import n2wordsES from 'n2words/lib/i18n/ES.mjs'``` -> Works in 1.15

**Comment by TylerVigario** [comment]
@Sergiobop I could get around this TypeScript issue by preceding the import line with `// @ts-ignore`. See the example below and let me know if this works for you as well.

```ts
// @ts-ignore
import n2words from 'n2words/i18n/EN'

console.log(n2words)
```

I'll look into providing a proper type definition file for TypeScript users.

**Comment by Sergiobop** [comment]
@TylerVigario Great, thank you for your fast response

Awesome package btw!

**Comment by TylerVigario** [comment]
@Sergiobop We thank you for your kind words! Going to close this for now but will follow up if, and when, I add proper TypeScript definitions.

**Comment by TylerVigario** [comment]
@Sergiobop I've gone into further discussion in #109 and created a wiki for importing in TypeScript - https://github.com/forzagreen/n2words/wiki/Importing-in-TypeScript

**Comment by Sergiobop** [comment]
Thank you @TylerVigario , i endep up importing the library like this:

// @ts-ignore
import n2wordsES from 'n2words/i18n/es.js';

And it's working

**Comment by TylerVigario** [comment]
@Sergiobop I've added typings in #112 which is included in `v1.16.3`. `// @ts-ignore` should no longer be needed. Cheers!
